-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.67.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25/12/2018 10:16:04 p.m.
-- Server version: 5.6.22-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE tatapp26_development;

--
-- Definition for table ar_internal_metadata
--
DROP TABLE IF EXISTS ar_internal_metadata;
CREATE TABLE ar_internal_metadata (
  `key` VARCHAR(255) NOT NULL,
  value VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table projects
--
DROP TABLE IF EXISTS projects;
CREATE TABLE projects (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  status INT(11) NOT NULL DEFAULT 1,
  tag VARCHAR(3) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table roles
--
DROP TABLE IF EXISTS roles;
CREATE TABLE roles (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  resource_type VARCHAR(255) DEFAULT NULL,
  resource_id BIGINT(20) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  INDEX index_roles_on_name (name),
  INDEX index_roles_on_name_and_resource_type_and_resource_id (name, resource_type, resource_id),
  INDEX index_roles_on_resource_type_and_resource_id (resource_type, resource_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table schema_migrations
--
DROP TABLE IF EXISTS schema_migrations;
CREATE TABLE schema_migrations (
  version VARCHAR(255) NOT NULL,
  PRIMARY KEY (version)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table users
--
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  employee_number VARCHAR(255) DEFAULT NULL,
  password_digest VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  username VARCHAR(255) NOT NULL DEFAULT '',
  encrypted_password VARCHAR(255) NOT NULL DEFAULT '',
  reset_password_token VARCHAR(255) DEFAULT NULL,
  reset_password_sent_at DATETIME DEFAULT NULL,
  remember_created_at DATETIME DEFAULT NULL,
  sign_in_count INT(11) NOT NULL DEFAULT 0,
  current_sign_in_at DATETIME DEFAULT NULL,
  last_sign_in_at DATETIME DEFAULT NULL,
  current_sign_in_ip VARCHAR(255) DEFAULT NULL,
  last_sign_in_ip VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX index_users_on_employee_number (employee_number),
  UNIQUE INDEX index_users_on_reset_password_token (reset_password_token),
  UNIQUE INDEX index_users_on_username (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 131
AVG_ROW_LENGTH = 468
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table users_roles
--
DROP TABLE IF EXISTS users_roles;
CREATE TABLE users_roles (
  user_id BIGINT(20) DEFAULT NULL,
  role_id BIGINT(20) DEFAULT NULL,
  INDEX index_users_roles_on_role_id (role_id),
  INDEX index_users_roles_on_user_id (user_id),
  INDEX index_users_roles_on_user_id_and_role_id (user_id, role_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 468
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table maps
--
DROP TABLE IF EXISTS maps;
CREATE TABLE maps (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  seats TEXT DEFAULT NULL,
  height INT(11) NOT NULL,
  width INT(11) NOT NULL,
  seats_total INT(11) NOT NULL,
  project_id BIGINT(20) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_rails_a90d6cd6e2 (project_id),
  CONSTRAINT fk_rails_a90d6cd6e2 FOREIGN KEY (project_id)
    REFERENCES projects(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 19
AVG_ROW_LENGTH = 1365
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table zones
--
DROP TABLE IF EXISTS zones;
CREATE TABLE zones (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  project_id BIGINT(20) NOT NULL,
  coordinates VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_rails_469356bd73 (project_id),
  CONSTRAINT fk_rails_469356bd73 FOREIGN KEY (project_id)
    REFERENCES projects(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 7
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table seats
--
DROP TABLE IF EXISTS seats;
CREATE TABLE seats (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  project_id BIGINT(20) NOT NULL,
  code VARCHAR(10) NOT NULL,
  status INT(11) NOT NULL DEFAULT 1,
  assignment_date DATE DEFAULT NULL,
  map_id BIGINT(20) NOT NULL,
  html_id VARCHAR(255) NOT NULL,
  `fixed` TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_rails_93e3b7506d (project_id),
  INDEX fk_rails_f35d21dd46 (map_id),
  CONSTRAINT fk_rails_93e3b7506d FOREIGN KEY (project_id)
    REFERENCES projects(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_rails_f35d21dd46 FOREIGN KEY (map_id)
    REFERENCES maps(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1127
AVG_ROW_LENGTH = 152
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table employees
--
DROP TABLE IF EXISTS employees;
CREATE TABLE employees (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  number VARCHAR(30) NOT NULL,
  admission_date DATE NOT NULL,
  birth_date DATE NOT NULL,
  status INT(11) NOT NULL DEFAULT 1,
  assignment_type INT(11) NOT NULL DEFAULT 1,
  seat_id BIGINT(20) DEFAULT NULL,
  project_id BIGINT(20) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  confirmed INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  INDEX fk_rails_c961385dd5 (seat_id),
  INDEX fk_rails_f3055ce412 (project_id),
  UNIQUE INDEX index_employees_on_number (number),
  CONSTRAINT fk_rails_c961385dd5 FOREIGN KEY (seat_id)
    REFERENCES seats(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_rails_f3055ce412 FOREIGN KEY (project_id)
    REFERENCES projects(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 130
AVG_ROW_LENGTH = 481
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table assignments
--
DROP TABLE IF EXISTS assignments;
CREATE TABLE assignments (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  project_id BIGINT(20) NOT NULL,
  employee_id BIGINT(20) NOT NULL,
  seat_id BIGINT(20) NOT NULL,
  assignment_date DATE NOT NULL,
  status INT(11) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_rails_1eb99de2cc (seat_id),
  INDEX fk_rails_4d3d2c839c (project_id),
  INDEX fk_rails_d0980e430f (employee_id),
  CONSTRAINT fk_rails_1eb99de2cc FOREIGN KEY (seat_id)
    REFERENCES seats(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_rails_4d3d2c839c FOREIGN KEY (project_id)
    REFERENCES projects(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_rails_d0980e430f FOREIGN KEY (employee_id)
    REFERENCES employees(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 16
AVG_ROW_LENGTH = 1260
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;